### ISSUE TITLE
Install break with new version of cachetools

### ISSUE THREAD

**Issue by panthony** [seomoz/reppy#102]
Hello there,

New version of cachetools (3.0.0) is released and it break reppy because the deprecated `missing` property was [removed](https://github.com/tkem/cachetools/blob/master/CHANGES.rst#v300-2018-11-04).

Currently reppy does not require any specific version:

```
reppy==0.4.9
  - cachetools [required: Any, installed: 3.0.0]
```

It should probably requires any 2.X instead

**Comment by zh0uquan** [comment]
Error as below:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/quan/Documents/sr_work/envs/fetcher/lib/python3.7/site-packages/reppy/cache/__init__.py", line 48, in __init__
    self.cache = LRUCache(maxsize=capacity, missing=self.missing)
TypeError: __init__() got an unexpected keyword argument 'missing'
```

**Comment by wumpus** [comment]
This bug was fixed on Nov 16 2018 and no one closed this bug @evanbattaglia
