### ISSUE TITLE
Is reppy thread-safe?

### ISSUE THREAD

**Issue by dmsalomon** [seomoz/reppy#117]
I apologize in advance if this is the wrong forum to ask this question.

I am using reppy for a mutlithreaded web crawler, and would like to know if the RobotCache is thread safe. If not, would the solution be as simple as wrapping all uses of the cache with a lock?

**Comment by dlecocq** [comment]
Not at all the wrong forum for questions like that! :-)

Yes, it is thread safe. The fetch for any given `robots.txt` URL is wrapped in a `threading.Lock` in this class (https://github.com/seomoz/reppy/blob/master/reppy/cache/__init__.py#L14) as part of the cache.

For its Python-based crawlers, Moz primarily uses `gevent` (or did when I last worked there), and this is also compatible with `gevent`.

**Comment by dmsalomon** [comment]
Thanks very much! I think `gevent` is a bit overkill for my needs, but I appreciate the suggestion.

**Comment by dmsalomon** [comment]
> I apologize in advance if this is the wrong forum to ask this question.
> 
> I am using reppy for a mutlithreaded web crawler, and would like to know if the RobotCache is thread safe. If not, would the solution be as simple as wrapping all uses of the cache with a lock?
