### ISSUE TITLE
User-agent: * should disallow everything

### ISSUE THREAD

**Issue by LeMoussel** [seomoz/reppy#128]
http://cocon.se/robots.txt has just `User-agent: *`.  It appears that they expect it to disallow everything. 

> robots.allowed('http://cocon.se/visualisation/', "*") : False

**Comment by wumpus** [comment]
cocon.se is wrong in that expectation. I don't think we should ignore the actual standard.

**Comment by LeMoussel** [comment]
Hummm ... With this robots.txt file, Goole allow this Url.
I also tested with [Scrapy/Protego](https://github.com/scrapy/protego), which allow this Url.
