### ISSUE TITLE
www.bestbuy.com/robots.txt false negative

### ISSUE THREAD

**Issue by enewhuis** [seomoz/reppy#20]
For some reason this URL

/site/Global/Free-Shipping/pcmcat276800050002.c?id=pcmcat276800050002

is disallowed by the library against this robots.txt from www.bestbuy.com

```
User-agent: *
Disallow: /*id=pcmcat140800050004
Disallow: /*id=pcmcat143800050032
Disallow: /nex/
Disallow: /shop/
Disallow: /*~~*
Disallow: /*jsessionid=
Disallow: /*dnmId=*
Disallow: /*ld=*lg=*rd=*
Disallow: /m/e/*
Disallow: /site/builder/*
Disallow: /site/promo/black-friday-*
Disallow: /site/promo/Black-Friday-*
Disallow: /*template=_gameDetailsTab
Disallow: /*template=_movieDetailsTab
Disallow: /*template=_musicDetailsTab
Disallow: /*template=_softwareDetailsTab
Disallow: /*template=_accessoriesTab
Disallow: /*template=_castAndCrewTab
Disallow: /*template=_editorialTab
Disallow: /*template=_episodesTab
Disallow: /*template=_protectionAndServicesTab
Disallow: /*template=_specificationsTab
```

**Comment by b4hand** [comment]
Closing this out, as it doesn't correspond to a bug in reppy but rather a server doing user agent based cloaking.

**Comment by dotjavafile** [comment]
I believe we need detailed usage documentation with example for reppy. The documentation do tell though that 
Customizing fetch
The fetch method accepts *args and **kwargs that are passed on to requests.get, allowing you to customize the way the fetch is executed:

robots = Robots.fetch('http://example.com/robots.txt', headers={...})

Hinting that we can send header info to fetch which calls requests.get

**Comment by b4hand** [comment]
That's true if you're using `fetch` directly, but this issue was discussing using RobotsCache which calls fetch indirectly with the arguments passed via the constructor for the cache.

**Comment by dotjavafile** [comment]
`Caching
There are two cache classes provided -- RobotsCache, which caches entire reppy.Robots objects, and AgentCache, which only caches the reppy.Agent relevant to a client. These caches duck-type the class that they cache for the purposes of checking if a URL is allowed:

from reppy.cache import RobotsCache
cache = RobotsCache(capacity=100)
cache.allowed('http://example.com/foo/bar', 'my-user-agent')

from reppy.cache import AgentCache
cache = AgentCache(agent='my-user-agent', capacity=100)
cache.allowed('http://example.com/foo/bar')
Like reppy.Robots.fetch, the cache constructory accepts a ttl_policy to inform the expiration of the fetched Robots objects, as well as *args and **kwargs to be passed to reppy.Robots.fetch.`

The documentation here doesn't explicitly provide an example that we can send a requests session object though.

**Comment by b4hand** [comment]
I would prefer if you present this information in the form of a pull request rather than commenting on this closed issue. If you open a PR for doc changes, they are very likely to be merged.
