### ISSUE TITLE
Inconsistencies across different versions

### ISSUE THREAD

**Issue by duncanmorris** [seomoz/reppy#28]
I tracked down an issue today, where my local version was (correctly) returning that a URL wasn't blocked by robots.txt, but on another the same code was returning that it was blocked.

My local machine is running python 2.7.10, where the other machine is running 2.7.6

I believe this is to do with way the `max` is sorted on the following line https://github.com/seomoz/reppy/blob/master/reppy/parser.py#L95

The robots.txt has the following (amongst other lines)

```
Allow: /hotels/$
Disallow: /hotels/*
```

Locally reppy said that `domain.com/hotels/` wasn't blocked, but the other machine reported it was.

The length of the regex's is the same, so I believe it defaulted to sorting the regex object, which I assume is what causes the inconsistency.

My proposal is to replace `max(allowed)[2]` with the following.

```
def sort_key(allowance):
    stripped_regex = allowance[1].pattern.replace('*', '')
    return (allowance[0], len(stripped_regex))
winner = sorted(allowed, key=sort_key, reverse=True)[0]
return winner[2]
```

This is based on the fact that the regex with the $ is more specific than the one with the star and hence should take precedence. I wasn't able to work out if this would cause any other issues.

**Comment by dlecocq** [comment]
Now that `reppy`'s been ported to C++ -- does this still reproduce on `master`?

**Comment by b4hand** [comment]
Closing as stale.
