### ISSUE TITLE
Failed when installing by using pip

### ISSUE THREAD

**Issue by yoshuajoe** [seomoz/reppy#44]
I've tried to install this reppy on Windows and I was using "pip install reppy". It didn't work. I got this message

error: command 'C:\\Users\\sysadm\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

**Comment by kwikiel** [comment]
Not working on Mac OS X Either. 

"Failed building wheel for reppy"

**Comment by dlecocq** [comment]
@yoshuajoe -- is that the extent of the error message? I don't have access to a Windows machine, so I have a limited ability to debug this.

**Comment by yoshuajoe** [comment]
I have solved this by selecting the earlier version of reppy (in my case, I'm using reppy v0.3.3)

**Comment by b4hand** [comment]
For what it is worth, v0.3.4 was the last pure Python version of reppy. My guess is you don't have Visual Studio installed which is why you can't compile the C++ library upon which reppy now depends.
