### ISSUE TITLE
ImportError: No module named robots

### ISSUE THREAD

**Issue by fili** [seomoz/reppy#60]
When installing with pip on Linux in a sandbox, then trying to use the module I get the following error:

from reppy.robots import Robots
ImportError: No module named robots

**Comment by b4hand** [comment]
Can you please include the definition of what you mean by sandbox? I just tried from a blank Ubuntu trusty64 vagrant box, and it works for me.

**Comment by fili** [comment]
GAE standard environment: https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27#installing_a_third-party_library

**Comment by b4hand** [comment]
I'm guessing since this works on a completely vanilla Ubuntu image using Vagrant, that your issue is specific to Google's App Engine environment. Are you able to use *any* third-party packages? Maybe try using a different package than `reppy`.

**Comment by fili** [comment]
A few packages that work fine within GAE: requests, urllib3, wtforms, pyopenssl, etc. 

Is your package a pure python module? I didn't see that information anywhere in the documentation. 

Thanks

**Comment by b4hand** [comment]
No, current versions of reppy depend on rep-cpp and url-cpp using cython.

**Comment by b4hand** [comment]
Resolving this as unable to reproduce, since we don't use GAE, and it seemingly works for others.
