### ISSUE TITLE
wrong implementation?

### ISSUE THREAD

**Issue by kootenpv** [seomoz/reppy#64]
Given:

    # manually created file at /robots.txt
    User-agent: *
    Disallow: /wp-admin/

Nothing is matched on the domain for `*`. How could that be possible?

According to the google spec, for a url:

    If allowed, allow it
    If disallowed, disallow it
    else, allow it.

**Comment by b4hand** [comment]
It would be preferable to produce a test case showing this rather than just providing a bug report. I'll go ahead and test this case out myself, but I'm suspicious because this code is being used in production by several crawlers that we use at Moz.

**Comment by b4hand** [comment]
```python
>>> import reppy
>>> from reppy import robots
>>> bot = robots.Robots.parse('http://example.com/robots.txt', '''# manually created file at /robots.txt
... User-agent: *
... Disallow: /wp-admin/
... ''')
>>> bot.allowed('/', 'agent')
True
```
It appears to work for me.

**Comment by kootenpv** [comment]
Could you try like `/test`, that should match as well? And what about `http://example.com/test`?
I think this is the example: https://www.crowdfundinsider.com/robots.txt

Note that nothing matching for me (I did not test '/' in your case). Anything other than `/wp-admin/` should match?

**Comment by b4hand** [comment]
I tried more than just `/` initially. Please produce a reproducible example that demonstrates whatever bug you are trying to report. I can't fix something that I can't reproduce.

**Comment by kootenpv** [comment]
Ah sorry, I thought it was clear from the code:

```python
from reppy.robots import Robots
robots = Robots.fetch('https://www.crowdfundinsider.com/robots.txt')

>>> robots.allowed('https://www.crowdfundinsider.com/tests', '*')
False
>>> robots.allowed('/tests', '*')
False
>>> robots.allowed('https://www.crowdfundinsider.com/', '*')
False

>>> robots.allowed('/', '*')
False
```

**Comment by b4hand** [comment]
Your issue is that you are sending the default requests User-Agent. It is not uncommon for public websites to ban generic programming language user-agents because they are believed to be either malicious or poorly written bots:

```sh
$ curl -i -H 'User-Agent: python-requests/2.10.0' https://www.crowdfundinsider.com/robots.txt
HTTP/1.1 403 Forbidden
Server: nginx
Date: Mon, 24 Apr 2017 20:20:12 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Keep-Alive: timeout=20

<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by kootenpv** [comment]
It's not uncommon to start with an unnamed bot, and as you get serious to come up with a header.

Either way, I was certainly not expecting a website to yield 403 on a lacking `User-Agent` in parsing the `robots.txt`, but in hindsight, it does make sense.

Still, from the perspective of the library, I think it makes sense to warn / raise to a user. It would really help to be explicit about this.

Thanks for the help.

**Comment by b4hand** [comment]
I can tell you from personal experience that we have crawled a large portion of the web, and it is *very* common for web sites to block generic user agents like `python-requests` and even `curl`. Notice that you *aren't* specifying no user agent. The underlying `requests` library *automatically* sends a default user-agent header with every request. This is not an issue with `reppy`.

There's nothing *technically wrong* with sending a user agent of `python-requests`, but it will get you banned by many sites.

**Comment by kootenpv** [comment]
@b4hand Right, thanks for correcting me all the way :) 

Indeed, if that's the default behavior, that's quite explainable. Still, perhaps `reppy` could be the one to warn on default header + 403 status with silently doing a universal block? I don't know, it sounds like a silly feature just for beginners, but these kind of explicit raises do help the next person.

Actually, if we are in fact supposed to be setting the `User-Agent` using the headers (why not make that an argument like `user_agent`?), then why wouldn't we have it also be a default in:

    bot.allowed('/some_path')

Using something like:

```python
def allowed(self, path, user_agent=None):
    if user_agent is None:
        user_agent = bot.headers['User-Agent']
```
I guess you get the idea.

**Comment by b4hand** [comment]
Technically, there's some complication around the name that is passed to the matcher versus the actual full header used by the User-Agent. Conventionally, these two things are *not* exactly the same thing. For example, Google's user-agent string is:

`Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`, but the match string is just `googlebot`. You need to pass the *match* string to the `allowed` function, but you need to pass a proper User-agent string to the fetcher.

**Comment by b4hand** [comment]
For what it is worth, this is a duplicate of #20.

It may be worth our while to update the docs to make it more clear that you should set a non-default user agent to prevent additional duplicate bugs like this one.
