### ISSUE TITLE
Suppress parsing errors

### ISSUE THREAD

**Issue by demalexx** [seomoz/reppy#76]
Now if there is error during parsing `robots.txt`, reppy outputs it like this:

```Could not parse date string 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/reppy/ttl.py", line 60, in ttl
    return max(self.minimum, parse_date(expires) - date)
  File "/usr/local/lib/python3.4/dist-packages/reppy/util.py", line 10, in parse_date
    raise ValueError("Invalid time.")
ValueError: Invalid time.
```
This isn't exception that could be handled by client code. Would be nice to have a way to suppress this error, or redirect somewhere else.

**Comment by b4hand** [comment]
Thank you for the bug report. What version of `reppy` are you using? Looking at the current code, [line 60](https://github.com/seomoz/reppy/blob/6145fbfd714618c8bf51185a221609d3387c1e1e/reppy/ttl.py#L60) appears to already be wrapped in a `try`/`except` block for `ValueError` already.

**Comment by demalexx** [comment]
Yes, it's wrapped in try/except. I mean it puts log message to console. Probably to avoid that message I just need to mute reppy logger somehow.

**Comment by dlecocq** [comment]
@demalexx you could set the logging level for `reppy` to `CRITICAL`, or remove all the handlers from that logging object (https://stackoverflow.com/a/7484605/173556)

**Comment by b4hand** [comment]
I'm thinking these log lines should probably be demoted to `logging.warn` rather than `logging.exception` which defaults to the ERROR level.
