### ISSUE TITLE
Is it possible to add wheels to this package?

### ISSUE THREAD

**Issue by yohannest** [seomoz/reppy#87]
While trying to install the package in windows i got the following error.
```
 building 'reppy.robots' extension
    error: Unable to find vcvarsall.bat
```
Unless i'm mistaken, this happens when the target machine does not have the compiler to convert the source code to binary. I can install the compiler needed but it would be more convenient if this moved to the wheels.

thanks

**Comment by b4hand** [comment]
The maintainers of this package do not have any Windows machines to perform compiles on and therefore cannot produce Windows wheels.
